  name: Cypress tests
  on: push
  jobs:
    cypress-tests:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3.1.0
         - name: Step name
           run: cd cypress && npm i && npm run cy:run:cypress

